events {}

http {
    upstream app_backend {
        server app-1:8080;
        server app-2:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://app_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}